### ISSUE TITLE
Code repository

### ISSUE THREAD

**Issue by nooralahzadeh** [justinlovelace/coherent-xray-report-generation#1]
Hi, 
I enjoyed reading your paper.
It would be great if you could update your code repository.
Thanks

**Comment by nooralahzadeh** [comment]
I especially interested in the Differentiable Language Generation module. Is there any way to access this part of the code?

**Comment by justinlovelace** [comment]
Hello @nooralahzadeh! Thanks for taking an interest. I just pushed the modeling code to the repo. The `TransformerGumbelModel` class in `models.py` is what you are looking for. If you have any additional questions then let me know.
